### ISSUE TITLE
役職ありの人も選ばれてしまう

### ISSUE THREAD

**Issue by potyama** [onokatio/nitkc-5j-committee#2]
すでに決まっている学籍番号を除外していないから、すでに役職がある人も選ばれてしまいます。

# 実行環境
ArchLinux 

# 対応策
すでに決まっている人の番号を用意しておく。
Seedから生成後、ソートし、上の番号と一致したら上の番号と一致した番号を+1 or -1する

例えば、1番がすでに役職きまっていて
1番が生成されたら+1して2をStudent[]のなかにいれる

が思いつきました

**Comment by onokatio** [comment]
ありがとう。既に役職付きの人の番号をStudent[]からdeleteするようにします。
